const dataCards = [
  {
    id: 1,
    category: "SKIN",
    discountText: "20% OFF",
    productImage: "images/pro1.png",
    productName: "HydraGlow Moisturizer",
    description: "Lightweight daily moisturizer for radiant, hydrated skin. Enriched with hyaluronic acid and natural oils to leave your skin soft, supple, and glowing all day.",
    comparePrice: "₹2500",
    price: "₹1999",
    ratingImage: "★★★★★",
    isBestSeller: true
  },
  {
    id: 2,
    category: "SKIN",
    discountText: "15% OFF",
    productImage: "images/pro2.png",
    productName: "GlowFix Vitamin C Serum",
    description: "Brightens dull skin and reduces dark spots naturally. This potent serum supports collagen production and enhances skin clarity with regular use.",
    comparePrice: "₹1800",
    price: "₹1530",
    ratingImage: "★★★★☆",
    isBestSeller: false
  },
  {
    id: 3,
    category: "SKIN",
    discountText: "10% OFF",
    productImage: "images/pro3.png",
    productName: "Aloe Soothing Gel",
    description: "Calms irritation and nourishes sensitive skin. Ideal for post-sun exposure, this gel cools, hydrates, and helps restore your skin’s natural barrier.",
    comparePrice: "₹1200",
    price: "₹1080",
    ratingImage: "★★★★☆",
    isBestSeller: false
  },
  {
    id: 4,
    category: "SKIN",
    discountText: "30% OFF",
    productImage: "images/pro4.png",
    productName: "Night Renewal Cream",
    description: "Deeply repairs skin while you sleep. Infused with peptides and retinol to reduce fine lines, firm texture, and promote cell turnover overnight.",
    comparePrice: "₹2800",
    price: "₹1960",
    ratingImage: "★★★★★",
    isBestSeller: true
  },
  {
    id: 6,
    category: "SKIN",
    discountText: "18% OFF",
    productImage: "images/pro6.png",
    productName: "SPF 50+ Sunblock Lotion",
    description: "Broad-spectrum UV protection for all skin types. Lightweight, non-greasy formula with water resistance for up to 6 hours.",
    comparePrice: "₹600",
    price: "₹492",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 7,
    category: "SKIN",
    discountText: "35% OFF",
    productImage: "images/pro7.png",
    productName: "Charcoal Detox Face Mask",
    description: "Removes blackheads and tightens pores instantly. Activated charcoal and clay draw out deep impurities and leave skin visibly clearer.",
    comparePrice: "₹2000",
    price: "₹1300",
    ratingImage: "★★★★★",
    isBestSeller: true
  },
  {
    id: 8,
    category: "SKIN",
    discountText: "12% OFF",
    productImage: "images/pro8.png",
    productName: "Rose Water Toner",
    description: "Hydrating facial mist with pure rose extract. Balances pH, tightens pores, and refreshes tired skin with a single spritz.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 9,
    category: "BODY",
    discountText: "12% OFF",
    productImage: "images/body-l1.png",
    productName: "Shea Butter Body Lotion",
    description: "Nourishes and softens dry, rough skin. Rich in shea butter and vitamin E, perfect for daily deep moisturization.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 10,
    category: "BODY",
    discountText: "12% OFF",
    productImage: "images/body-l2.png",
    productName: "Coffee Scrub Exfoliator",
    description: "Improves circulation and removes dead skin cells. Leaves your skin smooth, polished, and energized after every use.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: true
  },
  {
    id: 11,
    category: "BODY",
    discountText: "12% OFF",
    productImage: "images/body-l3.png",
    productName: "Aromatherapy Body Oil",
    description: "Soothing oil blend for relaxation and hydration. Infused with lavender and chamomile for a calming post-shower experience.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 12,
    category: "BODY",
    discountText: "12% OFF",
    productImage: "images/body-l4.png",
    productName: "Whitening Body Polish",
    description: "Gently exfoliates and brightens skin tone. Contains microcrystals and kojic acid to reveal glowing, even-toned skin.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 13,
    category: "FACE",
    discountText: "12% OFF",
    productImage: "images/face-w1.png",
    productName: "Pore-Minimizing Primer",
    description: "Blurs imperfections and smoothens makeup base. Controls oil and keeps your skin matte for hours.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: true
  },
  {
    id: 14,
    category: "FACE",
    discountText: "12% OFF",
    productImage: "images/face-w2.png",
    productName: "Mattifying Face Wash",
    description: "Controls oil and leaves skin feeling fresh. Formulated with tea tree and salicylic acid for acne-prone skin.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 15,
    category: "FACE",
    discountText: "12% OFF",
    productImage: "images/face-w3.png",
    productName: "Anti-Aging Face Cream",
    description: "Reduces wrinkles and firms skin texture. With peptides, collagen, and antioxidants for youthful radiance.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 16,
    category: "FACE",
    discountText: "12% OFF",
    productImage: "images/face-w4.png",
    productName: "HydraMist Facial Spray",
    description: "Instant hydration for dull, tired skin. Use anytime for a dewy refresh, even over makeup.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 17,
    category: "HAIR",
    discountText: "12% OFF",
    productImage: "images/hair1.png",
    productName: "Argan Oil Shampoo",
    description: "Restores shine and strengthens damaged hair. Sulfate-free and safe for color-treated hair.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 18,
    category: "HAIR",
    discountText: "12% OFF",
    productImage: "images/hair2.png",
    productName: "Keratin Smooth Conditioner",
    description: "Tames frizz and smoothens hair instantly. Helps seal split ends and adds long-lasting softness.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: true
  },
  {
    id: 19,
    category: "HAIR",
    discountText: "12% OFF",
    productImage: "images/hair3.png",
    productName: "Dry Scalp Relief Serum",
    description: "Soothes itchy scalp and promotes healthy roots. With peppermint and rosemary oil for natural scalp care.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 20,
    category: "HAIR",
    discountText: "12% OFF",
    productImage: "images/hair4.png",
    productName: "Volume Boost Hair Spray",
    description: "Adds body and lift to fine hair. Flexible hold and weightless volume without stickiness.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 21,
    category: "NAIL",
    discountText: "12% OFF",
    productImage: "images/nail1.png",
    productName: "Cuticle Oil Pen",
    description: "Hydrates and strengthens cuticles and nails. Portable pen design for mess-free application on the go.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 22,
    category: "NAIL",
    discountText: "12% OFF",
    productImage: "images/nail2.png",
    productName: "Glossy Top Coat",
    description: "High-shine protective nail polish finish. Helps prevent chipping and extends polish wear for days.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: true
  },
  {
    id: 23,
    category: "NAIL",
    discountText: "12% OFF",
    productImage: "images/nail3.png",
    productName: "Nail Strengthener Serum",
    description: "Repairs weak, brittle nails over time. Vitamin E and biotin boost nail growth and resilience.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  },
  {
    id: 24,
    category: "NAIL",
    discountText: "12% OFF",
    productImage: "images/nail4.png",
    productName: "Matte Finish Nail Paint",
    description: "Long-lasting matte color with quick dry. Available in elegant shades to suit every mood.",
    comparePrice: "₹700",
    price: "₹616",
    ratingImage: "★★★☆☆",
    isBestSeller: false
  }
];

export default dataCards;
